# Configurations H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Initialisation de la base
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8

# Configuration externalisée
mes-configs.limitDeProduits=5
server.port=9001